// Schema data for the ironedge block family.
// Kept out of ironedge.tsx (a "use client" module) so server code — notably the AI
// generation pipeline — can actually read it. See AI_ONBOARDING_PLAN.md.

export const IE_SCHEMAS: Record<string, any> = {
  IEHeader: { description: 'Fitness gym black sticky header', fields: [{ name: 'businessName', label: 'Business Name', type: 'text' }, { name: 'navLinks', label: 'Nav Links', type: 'array', arrayFields: [{ name: 'item', label: 'Link', type: 'text' }] }], defaultProps: { businessName: 'IRON EDGE', navLinks: ['HOME', 'PROGRAMS', 'ABOUT', 'RESULTS', 'PRICING'] } },
  IEHero: { description: 'High-contrast fitness hero with orange accent', fields: [{ name: 'headline', label: 'Headline', type: 'textarea' }, { name: 'subheading', label: 'Badge Text', type: 'text' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'backgroundImage', label: 'Background Image URL', type: 'text' }], defaultProps: { headline: 'STRONGER.\nLEANER.\nCONFIDENT.', subheading: 'REAL COACHING. REAL RESULTS.', description: '', backgroundImage: '' } },
  IEStats: { description: 'Orange stats bar on dark background', fields: [{ name: 'stats', label: 'Stats', type: 'array', arrayFields: [{ name: 'value', label: 'Value', type: 'text' }, { name: 'label', label: 'Label', type: 'text' }] }], defaultProps: { stats: [] } },
  IEServices: { description: 'Training programs dark grid', fields: [{ name: 'heading', label: 'Section Heading', type: 'text' }, { name: 'services', label: 'Programs', type: 'array', arrayFields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'icon', label: 'Icon', type: 'text' }, { name: 'desc', label: 'Description', type: 'textarea' }] }], defaultProps: { heading: 'Training Programs Built Around You', services: [] } },
  IEProcess: { description: 'Dark numbered process steps', fields: [{ name: 'heading', label: 'Heading', type: 'text' }, { name: 'steps', label: 'Steps', type: 'array', arrayFields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'desc', label: 'Description', type: 'textarea' }, { name: 'icon', label: 'Icon', type: 'text' }] }], defaultProps: { heading: 'Your Transformation Starts Here.', steps: [] } },
  IETestimonials: { description: 'Client transformation stories', fields: [{ name: 'heading', label: 'Heading', type: 'text' }, { name: 'reviews', label: 'Reviews', type: 'array', arrayFields: [{ name: 'name', label: 'Name', type: 'text' }, { name: 'role', label: 'Role', type: 'text' }, { name: 'quote', label: 'Quote', type: 'textarea' }] }], defaultProps: { heading: 'Client Transformations', reviews: [] } },
  IEPricing: { description: 'Dark pricing cards with orange accents', fields: [{ name: 'heading', label: 'Heading', type: 'text' }, { name: 'plans', label: 'Plans', type: 'array', arrayFields: [{ name: 'title', label: 'Plan Name', type: 'text' }, { name: 'price', label: 'Price (number)', type: 'text' }, { name: 'icon', label: 'Icon', type: 'text' }, { name: 'isPopular', label: 'Most Popular?', type: 'text' }, { name: 'features', label: 'Features', type: 'text' }] }], defaultProps: { heading: 'Simple, Transparent Pricing.', plans: [] } },
  IECTA: { description: 'Orange CTA section', fields: [{ name: 'heading', label: 'Heading', type: 'textarea' }, { name: 'buttonText', label: 'Button Text', type: 'text' }], defaultProps: { heading: "Your Best Body Is Closer Than You Think.\nStart Today.", buttonText: 'BOOK FREE STRATEGY CALL' } },
  IEFooter: { description: 'Minimal dark footer', fields: [{ name: 'businessName', label: 'Business Name', type: 'text' }], defaultProps: { businessName: 'IRON EDGE' } },
};
