// Schema data for the ridgeline block family.
// Kept out of ridgeline.tsx (a "use client" module) so server code — notably the AI
// generation pipeline — can actually read it. See AI_ONBOARDING_PLAN.md.

export const RL_SCHEMAS: Record<string, any> = {
  RLHeader: { description: 'Auto repair dark sticky header', fields: [{ name: 'businessName', label: 'Business Name', type: 'text' }, { name: 'tagline', label: 'Tagline', type: 'text' }, { name: 'phone', label: 'Phone', type: 'text' }, { name: 'ctaText', label: 'CTA Text', type: 'text' }], defaultProps: { businessName: 'RIDGE LINE AUTO', tagline: 'HONEST. FAST. RELIABLE.', phone: '(555) 874-0200', ctaText: 'BOOK ONLINE' } },
  RLHero: { description: 'Auto repair photo hero with red badge', fields: [{ name: 'badge', label: 'Badge Text', type: 'text' }, { name: 'title', label: 'Title', type: 'text' }, { name: 'subtitle', label: 'Subtitle', type: 'textarea' }, { name: 'ctaText', label: 'CTA Text', type: 'text' }, { name: 'bgImage', label: 'Background Image URL', type: 'text' }], defaultProps: { badge: 'Rated #1', title: 'Expert Auto Repair You Can Trust', subtitle: 'Transparent pricing. No surprises.', ctaText: 'BOOK APPOINTMENT', bgImage: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=2070' } },
  RLStats: { description: 'Dark gray stats bar', fields: [{ name: 'stats', label: 'Stats', type: 'array', arrayFields: [{ name: 'value', label: 'Value', type: 'text' }, { name: 'label', label: 'Label', type: 'text' }] }], defaultProps: { stats: [] } },
  RLServices: { description: 'Auto services grid with photos', fields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'subtitle', label: 'Subtitle', type: 'text' }, { name: 'services', label: 'Services', type: 'array', arrayFields: [{ name: 'title', label: 'Service Name', type: 'text' }, { name: 'icon', label: 'Icon Name', type: 'text' }, { name: 'desc', label: 'Description', type: 'textarea' }] }], defaultProps: { title: 'Full-Service Auto Care', subtitle: '', services: [] } },
  RLProcess: { description: 'Dark process steps section', fields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'steps', label: 'Steps', type: 'array', arrayFields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'desc', label: 'Description', type: 'textarea' }, { name: 'icon', label: 'Icon', type: 'text' }] }], defaultProps: { title: 'How it works', steps: [] } },
  RLTestimonials: { description: 'Customer review cards', fields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'reviews', label: 'Reviews', type: 'array', arrayFields: [{ name: 'name', label: 'Name', type: 'text' }, { name: 'role', label: 'Role', type: 'text' }, { name: 'quote', label: 'Quote', type: 'textarea' }] }], defaultProps: { title: 'What Our Customers Say', reviews: [] } },
  RLCTA: { description: 'Red CTA section', fields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'subtitle', label: 'Subtitle', type: 'text' }, { name: 'buttonText', label: 'Button Text', type: 'text' }], defaultProps: { title: "Car Trouble? We've Got You.", subtitle: 'Book online in 60 seconds.', buttonText: 'BOOK YOUR APPOINTMENT' } },
  RLFooter: { description: 'Auto shop footer with contact details', fields: [{ name: 'businessName', label: 'Business Name', type: 'text' }, { name: 'phone', label: 'Phone', type: 'text' }, { name: 'email', label: 'Email', type: 'text' }, { name: 'address', label: 'Address', type: 'text' }], defaultProps: { businessName: 'RIDGE LINE AUTO', phone: '(555) 874-0200', email: 'service@ridgelineauto.com', address: '2847 Commerce Blvd' } },
};
