// Schema data for the sterlinglaw block family.
// Kept out of sterlinglaw.tsx (a "use client" module) so server code — notably the AI
// generation pipeline — can actually read it. See AI_ONBOARDING_PLAN.md.

export const SL_SCHEMAS: Record<string, any> = {
  SLHeader: { description: 'Law firm sticky header with logo and navigation', fields: [{ name: 'businessName', label: 'Business Name', type: 'text' }, { name: 'navLinks', label: 'Nav Links', type: 'array', arrayFields: [{ name: 'item', label: 'Link', type: 'text' }] }], defaultProps: { businessName: 'STERLING LAW', navLinks: ['HOME', 'PRACTICE AREAS', 'ABOUT US', 'RESULTS', 'CONTACT'] } },
  SLHero: { description: 'Full-height law firm hero with navy overlay', fields: [{ name: 'headline', label: 'Headline', type: 'textarea' }, { name: 'subheading', label: 'Subheading', type: 'text' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'backgroundImage', label: 'Background Image URL', type: 'text' }], defaultProps: { headline: 'TRUSTED.\nEXPERIENCED.\nRESULTS-DRIVEN.', subheading: 'YOUR RIGHTS. OUR PRIORITY.', description: 'Aggressive representation for individuals and businesses.', backgroundImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=2070' } },
  SLStats: { description: 'Gold stats bar with key metrics', fields: [{ name: 'stats', label: 'Stats', type: 'array', arrayFields: [{ name: 'value', label: 'Value', type: 'text' }, { name: 'label', label: 'Label', type: 'text' }, { name: 'icon', label: 'Icon', type: 'text' }] }], defaultProps: { stats: [{ value: '25+', label: 'Years of Excellence', icon: 'Scale' }, { value: '$50M+', label: 'Recovered', icon: 'Shield' }] } },
  SLServices: { description: 'Practice areas grid with icon cards', fields: [{ name: 'heading', label: 'Section Heading', type: 'text' }, { name: 'services', label: 'Practice Areas', type: 'array', arrayFields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'icon', label: 'Icon Name', type: 'text' }, { name: 'desc', label: 'Description', type: 'textarea' }] }], defaultProps: { heading: 'Our Practice Areas', services: [] } },
  SLProcess: { description: 'Navy process steps section', fields: [{ name: 'heading', label: 'Section Heading', type: 'textarea' }, { name: 'steps', label: 'Steps', type: 'array', arrayFields: [{ name: 'title', label: 'Title', type: 'text' }, { name: 'desc', label: 'Description', type: 'textarea' }, { name: 'icon', label: 'Icon', type: 'text' }] }], defaultProps: { heading: 'How We Work', steps: [] } },
  SLTestimonials: { description: 'Gold-accented client testimonials', fields: [{ name: 'heading', label: 'Section Heading', type: 'text' }, { name: 'reviews', label: 'Reviews', type: 'array', arrayFields: [{ name: 'name', label: 'Name', type: 'text' }, { name: 'role', label: 'Role', type: 'text' }, { name: 'quote', label: 'Quote', type: 'textarea' }, { name: 'img', label: 'Photo URL', type: 'text' }] }], defaultProps: { heading: 'Client Success Stories', reviews: [] } },
  SLCTA: { description: 'Navy CTA section with gold button', fields: [{ name: 'heading', label: 'Heading', type: 'textarea' }, { name: 'buttonText', label: 'Button Text', type: 'text' }], defaultProps: { heading: "Don't Navigate the Legal System Alone.\nGet Expert Representation Today.", buttonText: 'SCHEDULE FREE CONSULTATION' } },
  SLFooter: { description: 'Law firm footer with disclaimer', fields: [{ name: 'businessName', label: 'Business Name', type: 'text' }], defaultProps: { businessName: 'STERLING LAW' } },
};
