export interface Clip {
  id: string;
  name: string;
  videoUrl: string;
  thumbnailUrl: string;
  category: string;
  tags: string[];
  duration: number;
  width: number;
  height: number;
}

export const CATEGORY_MAP: Record<string, string> = {
  "spear": "槍/長柄武器 (Spear)",
  "daily-other": "日常與其他 (Daily/Other)",
  "emotion": "表情與情感 (Emotion)",
  "shield": "盾牌與防禦 (Shield/Defend)",
  "direction-game": "遊戲導演/演出 (Direction/Game)",
  "attack": "普通攻擊 (Attack)",
  "walk": "行走移動 (Walk)",
  "combat-ready": "戰鬥準備 (Combat Ready)",
  "sword": "劍/雙手劍 (Sword)",
  "surprise": "驚訝反應 (Surprise)",
  "grab-release-lift": "抓取與抱起 (Grab/Lift)",
  "body": "身體與格鬥 (Body/Melee)",
  "death": "擊敗與死亡 (Death)",
  "hit": "受擊反應 (Hit)",
  "gun": "槍械/手槍 (Gun)",
  "run": "跑步/突進 (Run)",
  "return": "收招/收刀 (Return)",
  "movement-other": "其他移動 (Movement/Other)",
  "jump": "跳躍/下落 (Jump)",
  "bow": "弓箭/遠程 (Bow)",
  "dash": "閃避/突進 (Dash)"
};

export const CLIPS: Clip[] = [
  {
    "id": "LI34IOZEBKJ4I",
    "name": "遊戲 히어로즈아레나 登場 槍",
    "videoUrl": "https://assets.reflix.dev/previews/LI34IOZEBKJ4I.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LI34IOZEBKJ4I.webp",
    "category": "spear",
    "tags": [
      "遊戲",
      "登場",
      "히어로즈아레나",
      "槍",
      "무기",
      "인遊戲"
    ],
    "duration": 4.167,
    "width": 1280,
    "height": 590
  },
  {
    "id": "L3TR52T4JUWRC",
    "name": "演出 靈魂急轉彎 慶祝 友好 흑인",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T4JUWRC.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T4JUWRC.webp",
    "category": "daily-other",
    "tags": [
      "靈魂急轉彎",
      "慶祝",
      "演出",
      "動畫"
    ],
    "duration": 4.598,
    "width": 1920,
    "height": 804
  },
  {
    "id": "MBG88U114GYIZ",
    "name": "演出 奧術 2 걱정 혼란 두려움 무서움 아이 지하철 열차 전철",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U114GYIZ.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U114GYIZ.webp",
    "category": "emotion",
    "tags": [
      "演出",
      "아이",
      "걱정",
      "혼란",
      "두려움",
      "무서움",
      "奧術",
      "차기",
      "한숨",
      "공포",
      "겁먹음",
      "불안",
      "고민",
      "動畫"
    ],
    "duration": 10.410998,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L96TUEKAHOU4U",
    "name": "遊戲 鐵槌 揮舞 盾牌 1 雙持",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEKAHOU4U.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEKAHOU4U.webp",
    "category": "shield",
    "tags": [
      "揮舞",
      "鐵槌",
      "攻擊",
      "盾牌",
      "遊戲",
      "雙持",
      "무기",
      "교전",
      "데모릴"
    ],
    "duration": 7.4,
    "width": 1280,
    "height": 722
  },
  {
    "id": "MJPTGPZYBCHAO",
    "name": "演出 노레스트포더위키드 슬픔 소식 전달 죽음 놀람 걱정",
    "videoUrl": "https://assets.reflix.dev/previews/MJPTGPZYBCHAO.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MJPTGPZYBCHAO.webp",
    "category": "direction-game",
    "tags": [
      "놀람",
      "演出",
      "슬픔",
      "노레스트포더위키드",
      "걱정",
      "死亡",
      "소식",
      "전달",
      "건네주기",
      "고민",
      "불안",
      "침울",
      "우울",
      "電影感"
    ],
    "duration": 9.616667,
    "width": 1280,
    "height": 720
  },
  {
    "id": "MP7XQ36MZM880",
    "name": "演出 女性 踢擊 閃避 受擊 교전 전투 攻擊 일대다 格鬥",
    "videoUrl": "https://assets.reflix.dev/previews/MP7XQ36MZM880.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MP7XQ36MZM880.webp",
    "category": "attack",
    "tags": [
      "演出",
      "女性",
      "차기",
      "閃避",
      "受擊",
      "교전",
      "전투",
      "攻擊",
      "일대다",
      "格鬥"
    ],
    "duration": 4.04,
    "width": 1280,
    "height": 720
  },
  {
    "id": "MBG88U2YPBT3F",
    "name": "演出 奧術 2 發現 刺眼",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U2YPBT3F.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U2YPBT3F.webp",
    "category": "direction-game",
    "tags": [
      "演出",
      "發現",
      "눈",
      "刺眼",
      "발",
      "奧術",
      "動畫"
    ],
    "duration": 5.610998,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "LO3WUPY4O9EZZ",
    "name": "演出 젤다의전설 行走 멈추기 돌아보기 돌기 무쌍",
    "videoUrl": "https://assets.reflix.dev/previews/LO3WUPY4O9EZZ.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LO3WUPY4O9EZZ.webp",
    "category": "walk",
    "tags": [
      "演出",
      "젤다의전설",
      "行走",
      "멈추기",
      "돌기",
      "돌아보기",
      "電影感"
    ],
    "duration": 10.7,
    "width": 1280,
    "height": 720
  },
  {
    "id": "MBG88U4EVQEMY",
    "name": "演出 奧術 2 戰爭 信號 準備 작전",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U4EVQEMY.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U4EVQEMY.webp",
    "category": "combat-ready",
    "tags": [
      "演出",
      "戰爭",
      "準備",
      "信號",
      "신음",
      "奧術",
      "교전",
      "動畫"
    ],
    "duration": 12.692993,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "MPJPOGVTOKZ5K",
    "name": "遊戲 드래곤에이지 女性 한손 1타 法杖 攻擊 收招 시전 魔法師",
    "videoUrl": "https://assets.reflix.dev/previews/MPJPOGVTOKZ5K.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MPJPOGVTOKZ5K.webp",
    "category": "attack",
    "tags": [
      "遊戲",
      "드래곤에이지",
      "女性",
      "한손",
      "1타",
      "法杖",
      "攻擊",
      "收招",
      "시전",
      "魔法師"
    ],
    "duration": 3.8,
    "width": 1280,
    "height": 720
  },
  {
    "id": "LO29PWXTFPO0I",
    "name": "遊戲 DNF/地下城與勇士 雙持 劍 단劍 올려치기 베기",
    "videoUrl": "https://assets.reflix.dev/previews/LO29PWXTFPO0I.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LO29PWXTFPO0I.webp",
    "category": "sword",
    "tags": [
      "遊戲",
      "劍",
      "雙持",
      "短劍",
      "DNF/地下城與勇士",
      "베기",
      "올려치기",
      "올려베기",
      "무기",
      "攻擊",
      "교전",
      "인遊戲"
    ],
    "duration": 1.733333,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L3TR52T5WAHWZ",
    "name": "演出 靈魂急轉彎 인기척 놀람",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T5WAHWZ.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T5WAHWZ.webp",
    "category": "surprise",
    "tags": [
      "靈魂急轉彎",
      "놀람",
      "인기척",
      "演出",
      "動畫"
    ],
    "duration": 2.369,
    "width": 1920,
    "height": 804
  },
  {
    "id": "MOY8L2G8DK0UF",
    "name": "演出 女性 잡기 들기 관찰 고민 클로즈업",
    "videoUrl": "https://assets.reflix.dev/previews/MOY8L2G8DK0UF.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MOY8L2G8DK0UF.webp",
    "category": "grab-release-lift",
    "tags": [
      "잡기",
      "올리기",
      "관찰",
      "고민",
      "클로즈업",
      "女性",
      "演出"
    ],
    "duration": 3.018594,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L96TUEK7AJSIV",
    "name": "遊戲 劍 收招 1 양손",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEK7AJSIV.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEK7AJSIV.webp",
    "category": "sword",
    "tags": [
      "劍",
      "收招",
      "遊戲",
      "양손",
      "무기",
      "인遊戲"
    ],
    "duration": 2.4,
    "width": 1280,
    "height": 1066
  },
  {
    "id": "L96TUEK85H8S1",
    "name": "遊戲 劍은사막 女性 格鬥가 拳擊 지르기 收招 (5) 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEK85H8S1.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEK85H8S1.webp",
    "category": "body",
    "tags": [
      "黑色沙漠",
      "格鬥가",
      "收招",
      "女性",
      "拳擊",
      "지르기",
      "몸",
      "攻擊",
      "遊戲",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 5.4,
    "width": 1280,
    "height": 960
  },
  {
    "id": "MBG88U39VQGJ2",
    "name": "演出 奧術 2 생각 고민 죄책감 자책",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U39VQGJ2.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U39VQGJ2.webp",
    "category": "emotion",
    "tags": [
      "演出",
      "고민",
      "생각",
      "자책",
      "책",
      "죄책감",
      "奧術",
      "걱정",
      "불안",
      "두려움",
      "무서움",
      "공포",
      "겁먹음",
      "動畫"
    ],
    "duration": 6.315011,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L96TUEKA0CTWG",
    "name": "遊戲 스트레인지매직 劍 회전 2 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEKA0CTWG.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEKA0CTWG.webp",
    "category": "sword",
    "tags": [
      "劍",
      "회전",
      "회전베기",
      "스트레인지매직",
      "攻擊",
      "遊戲",
      "무기",
      "교전",
      "動畫"
    ],
    "duration": 1.28,
    "width": 1280,
    "height": 544
  },
  {
    "id": "L96TUEK87IHST",
    "name": "遊戲 劍은사막 발키리 女性 格鬥가 4타 회전차기 踢擊 收招 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEK87IHST.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEK87IHST.webp",
    "category": "body",
    "tags": [
      "黑色沙漠",
      "格鬥가",
      "收招",
      "차기",
      "발키리",
      "女性",
      "몸",
      "攻擊",
      "회전차기",
      "遊戲",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 4.8,
    "width": 1280,
    "height": 960
  },
  {
    "id": "MBG88U1YPZUOR",
    "name": "演出 奧術 2 놀람 돌아보기 명령 戰爭",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U1YPZUOR.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U1YPZUOR.webp",
    "category": "attack",
    "tags": [
      "演出",
      "놀람",
      "돌아보기",
      "戰爭",
      "명령",
      "奧術",
      "교전",
      "攻擊",
      "動畫"
    ],
    "duration": 10.069002,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "LO3WUPY4XYOY5",
    "name": "演出 나루토 네지 格鬥가 일대다 교전 레이아웃",
    "videoUrl": "https://assets.reflix.dev/previews/LO3WUPY4XYOY5.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LO3WUPY4XYOY5.webp",
    "category": "body",
    "tags": [
      "演出",
      "레이아웃",
      "교전",
      "格鬥가",
      "일대다",
      "나루토",
      "네지",
      "攻擊",
      "電影感"
    ],
    "duration": 10.116667,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L952BPJQCC7E6",
    "name": "遊戲 채찍 揮舞 突刺 1 한손",
    "videoUrl": "https://assets.reflix.dev/previews/L952BPJQCC7E6.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L952BPJQCC7E6.webp",
    "category": "attack",
    "tags": [
      "揮舞",
      "突刺",
      "채찍",
      "攻擊",
      "遊戲",
      "한손",
      "무기",
      "교전",
      "데모릴"
    ],
    "duration": 4.934,
    "width": 1280,
    "height": 962
  },
  {
    "id": "MO9ZAB96P6TY3",
    "name": "遊戲 女性 한손 5타+ 劍 跳躍 落地 空中 攻擊 베기 내려찍기",
    "videoUrl": "https://assets.reflix.dev/previews/MO9ZAB96P6TY3.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MO9ZAB96P6TY3.webp",
    "category": "sword",
    "tags": [
      "遊戲",
      "女性",
      "한손",
      "5타+",
      "劍",
      "跳躍",
      "落地",
      "空中",
      "攻擊",
      "베기",
      "내려찍기"
    ],
    "duration": 11.748012,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "MBG88U4D8X6M6",
    "name": "演出 奧術 2 戰爭 사슬 교전 일대다 死亡",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U4D8X6M6.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U4D8X6M6.webp",
    "category": "death",
    "tags": [
      "演出",
      "교전",
      "死亡",
      "戰爭",
      "일대다",
      "奧術",
      "攻擊",
      "動畫"
    ],
    "duration": 11.115011,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "LO29PWXTOQMI6",
    "name": "遊戲 DNF/地下城與勇士 女性 挫敗 絕望 受擊",
    "videoUrl": "https://assets.reflix.dev/previews/LO29PWXTOQMI6.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LO29PWXTOQMI6.webp",
    "category": "hit",
    "tags": [
      "遊戲",
      "女性",
      "DNF/地下城與勇士",
      "맞음",
      "挫敗",
      "絕望",
      "절규",
      "인遊戲"
    ],
    "duration": 4.1,
    "width": 1280,
    "height": 720
  },
  {
    "id": "LO29PWXTKR9HC",
    "name": "遊戲 이승원 한손 槍械 換彈",
    "videoUrl": "https://assets.reflix.dev/previews/LO29PWXTKR9HC.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LO29PWXTKR9HC.webp",
    "category": "gun",
    "tags": [
      "遊戲",
      "한손",
      "槍械",
      "이승원",
      "換彈",
      "무기",
      "데모릴"
    ],
    "duration": 1.1,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L96TUEK7LJX68",
    "name": "遊戲 劍은사막 格鬥가 拳擊 2타 跳躍 올려치기 내려찍기 下蹲 落地 收招 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEK7LJX68.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEK7LJX68.webp",
    "category": "body",
    "tags": [
      "黑色沙漠",
      "格鬥가",
      "收招",
      "下蹲",
      "올려치기",
      "跳躍",
      "拳擊",
      "落地",
      "올려베기",
      "몸",
      "攻擊",
      "遊戲",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 2.9,
    "width": 1280,
    "height": 960
  },
  {
    "id": "L96TUEK9R54S9",
    "name": "遊戲 劍은사막 女性 格鬥가 회전차기 收招 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEK9R54S9.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEK9R54S9.webp",
    "category": "body",
    "tags": [
      "黑色沙漠",
      "格鬥가",
      "收招",
      "女性",
      "몸",
      "회전차기",
      "攻擊",
      "遊戲",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 4.5,
    "width": 1280,
    "height": 960
  },
  {
    "id": "L9PBMMX6TJ7N7",
    "name": "遊戲 뒤로가기 後退 跑步 공차기 踢擊 슛 足球 bip",
    "videoUrl": "https://assets.reflix.dev/previews/L9PBMMX6TJ7N7.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L9PBMMX6TJ7N7.webp",
    "category": "run",
    "tags": [
      "跑步",
      "뒤로가기",
      "後退",
      "차기",
      "攻擊",
      "遊戲",
      "이동",
      "교전",
      "실사/포즈"
    ],
    "duration": 9.7,
    "width": 1280,
    "height": 720
  },
  {
    "id": "LMTYNSYFK4FN6",
    "name": "遊戲 槍 揮舞 회전 收招",
    "videoUrl": "https://assets.reflix.dev/previews/LMTYNSYFK4FN6.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LMTYNSYFK4FN6.webp",
    "category": "return",
    "tags": [
      "遊戲",
      "收招",
      "揮舞",
      "槍",
      "회전",
      "攻擊",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 4.933333,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L96TUEKAW3VRP",
    "name": "遊戲 女性 槍 전투 待機 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEKAW3VRP.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEKAW3VRP.webp",
    "category": "spear",
    "tags": [
      "待機",
      "女性",
      "전투",
      "槍",
      "遊戲",
      "무기",
      "데모릴"
    ],
    "duration": 1.441,
    "width": 1280,
    "height": 1330
  },
  {
    "id": "MNX3B3A9Y5XZ7",
    "name": "演出 멸망의파도 女性 멈추기 跑步 아쉬움 역 지하철 개찰구",
    "videoUrl": "https://assets.reflix.dev/previews/MNX3B3A9Y5XZ7.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MNX3B3A9Y5XZ7.webp",
    "category": "movement-other",
    "tags": [
      "演出",
      "멸망의파도",
      "女性",
      "멈추기",
      "跑步",
      "아쉬움",
      "역",
      "지하철",
      "개찰구"
    ],
    "duration": 4,
    "width": 640,
    "height": 360
  },
  {
    "id": "MBG88U1WU2GL3",
    "name": "演出 奧術 2 놀람 경계 멈추기 跑步",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U1WU2GL3.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U1WU2GL3.webp",
    "category": "run",
    "tags": [
      "演出",
      "놀람",
      "跑步",
      "멈추기",
      "조심",
      "奧術",
      "動畫"
    ],
    "duration": 13.652993,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L3TR52T645D50",
    "name": "演出 스트레인지매직 女性 精靈 飛行 51",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T645D50.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T645D50.webp",
    "category": "daily-other",
    "tags": [
      "스트레인지매직",
      "女性",
      "飛行",
      "精靈",
      "演出",
      "動畫"
    ],
    "duration": 3.968,
    "width": 1280,
    "height": 544
  },
  {
    "id": "L3TR52T73G586",
    "name": "演出 靈魂急轉彎 팔짱 3",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T73G586.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T73G586.webp",
    "category": "daily-other",
    "tags": [
      "靈魂急轉彎",
      "팔짱",
      "演出",
      "動畫"
    ],
    "duration": 2.787,
    "width": 1920,
    "height": 804
  },
  {
    "id": "LMTYNSYF2JZ3A",
    "name": "遊戲 고스트오브쓰시마 한손 劍 跳躍 내려치기",
    "videoUrl": "https://assets.reflix.dev/previews/LMTYNSYF2JZ3A.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LMTYNSYF2JZ3A.webp",
    "category": "jump",
    "tags": [
      "遊戲",
      "한손",
      "跳躍",
      "劍",
      "고스트오브쓰시마",
      "내려치기",
      "攻擊",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 3.603604,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "MJPTGQ000XVVN",
    "name": "演出 디아블로 交互 開啟 寶箱 무덤",
    "videoUrl": "https://assets.reflix.dev/previews/MJPTGQ000XVVN.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MJPTGQ000XVVN.webp",
    "category": "daily-other",
    "tags": [
      "演出",
      "디아블로",
      "開啟",
      "寶箱",
      "交互",
      "무덤덤",
      "電影感"
    ],
    "duration": 3.563091,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L96TUEK8UIQ9K",
    "name": "遊戲 劍은사막 발키리 女性 盾牌 2타 내려치기 베기 收招 1 雙持 劍",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEK8UIQ9K.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEK8UIQ9K.webp",
    "category": "shield",
    "tags": [
      "黑色沙漠",
      "收招",
      "발키리",
      "盾牌",
      "베기",
      "女性",
      "攻擊",
      "遊戲",
      "雙持",
      "劍",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 3.85,
    "width": 1280,
    "height": 960
  },
  {
    "id": "MBG88U2UTL2K0",
    "name": "演出 奧術 2 물건 들기 벽 조작 꺼내기",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U2UTL2K0.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U2UTL2K0.webp",
    "category": "direction-game",
    "tags": [
      "演出",
      "물건",
      "올리기",
      "벽",
      "조작",
      "꺼내기",
      "奧術",
      "집기",
      "動畫"
    ],
    "duration": 3.947007,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "LO6IBUNCDUR52",
    "name": "演出 젤다의전설 跑步 멈추기 女性 왕국의눈물",
    "videoUrl": "https://assets.reflix.dev/previews/LO6IBUNCDUR52.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LO6IBUNCDUR52.webp",
    "category": "run",
    "tags": [
      "女性",
      "演出",
      "젤다의전설",
      "멈추기",
      "跑步",
      "電影感"
    ],
    "duration": 6.5,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L3TR52T7RL9JR",
    "name": "演出 클라우스 삿대질 손가락질 구분 구별",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T7RL9JR.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T7RL9JR.webp",
    "category": "daily-other",
    "tags": [
      "손가락질",
      "클라우스",
      "손",
      "演出",
      "가리키기",
      "動畫"
    ],
    "duration": 3.723,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "LI34IOZE7BNJO",
    "name": "遊戲 유승진 서머너즈워 크로니클 오라클 女性 魔法師 시전 攻擊 收招",
    "videoUrl": "https://assets.reflix.dev/previews/LI34IOZE7BNJO.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LI34IOZE7BNJO.webp",
    "category": "return",
    "tags": [
      "遊戲",
      "女性",
      "魔法師",
      "收招",
      "攻擊",
      "유승진",
      "서머너즈워",
      "크로니클",
      "오라클",
      "시전",
      "技能",
      "마법",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 5,
    "width": 1280,
    "height": 720
  },
  {
    "id": "LP56H8Q5NUGO4",
    "name": "遊戲 원신 女性 살펴보기 소셜 5",
    "videoUrl": "https://assets.reflix.dev/previews/LP56H8Q5NUGO4.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LP56H8Q5NUGO4.webp",
    "category": "emote-ingame",
    "tags": [
      "소셜",
      "원신",
      "女性",
      "살펴보기",
      "관찰",
      "감정표현",
      "살피기",
      "遊戲",
      "인遊戲"
    ],
    "duration": 8.668005,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L3TR52T4YEPKD",
    "name": "演出 奧術 쫄음 두려움 무서움 긴장",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T4YEPKD.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T4YEPKD.webp",
    "category": "emotion",
    "tags": [
      "奧術",
      "두려움",
      "무서움",
      "긴장감",
      "공포",
      "겁먹음",
      "움츠러듬",
      "演出",
      "불안",
      "걱정",
      "고민",
      "動畫"
    ],
    "duration": 6.834,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L3TR52T9LR3OS",
    "name": "演出 리그오브레전드 閃避",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T9LR3OS.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T9LR3OS.webp",
    "category": "daily-other",
    "tags": [
      "閃避",
      "리그오브레전드",
      "演出",
      "電影感"
    ],
    "duration": 2.693515,
    "width": 1280,
    "height": 720
  },
  {
    "id": "MBG88U1RXY5MG",
    "name": "演出 奧術 2 기待機 컵 닦기 여유",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U1RXY5MG.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U1RXY5MG.webp",
    "category": "emotion",
    "tags": [
      "演出",
      "여유",
      "닦기",
      "컵",
      "기待機",
      "기대감",
      "奧術",
      "待機",
      "설렘",
      "들뜸",
      "느긋함",
      "動畫"
    ],
    "duration": 8.875011,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "MJPTGQ0X2KPWI",
    "name": "演出 젠레스존제로 소리치기 간절함 화남 놀람",
    "videoUrl": "https://assets.reflix.dev/previews/MJPTGQ0X2KPWI.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MJPTGQ0X2KPWI.webp",
    "category": "direction-game",
    "tags": [
      "젠레스존제로",
      "놀람",
      "演出",
      "화남",
      "간절함",
      "소리치기",
      "제발",
      "부탁",
      "화내기",
      "분노",
      "電影感"
    ],
    "duration": 5.525333,
    "width": 1280,
    "height": 720
  },
  {
    "id": "MJPTGPZZ975A8",
    "name": "演出 노레스트포더위키드 여유 확신",
    "videoUrl": "https://assets.reflix.dev/previews/MJPTGPZZ975A8.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MJPTGPZZ975A8.webp",
    "category": "direction-game",
    "tags": [
      "演出",
      "노레스트포더위키드",
      "여유",
      "확신",
      "결의",
      "각오",
      "다짐",
      "의지",
      "느긋함",
      "電影感"
    ],
    "duration": 7.483333,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L952BPJQUJ3L4",
    "name": "遊戲 女性 劍 死亡 1",
    "videoUrl": "https://assets.reflix.dev/previews/L952BPJQUJ3L4.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L952BPJQUJ3L4.webp",
    "category": "death",
    "tags": [
      "女性",
      "死亡",
      "劍",
      "遊戲",
      "무기",
      "데모릴"
    ],
    "duration": 2.438095,
    "width": 1280,
    "height": 720
  },
  {
    "id": "MBG88U4LZUPA6",
    "name": "演出 奧術 2 초라함 우울 한숨",
    "videoUrl": "https://assets.reflix.dev/previews/MBG88U4LZUPA6.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MBG88U4LZUPA6.webp",
    "category": "emotion",
    "tags": [
      "演出",
      "한숨",
      "奧術",
      "우울",
      "숨",
      "걱정",
      "고민",
      "불안",
      "두려움",
      "무서움",
      "공포",
      "겁먹음",
      "動畫"
    ],
    "duration": 8.32,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L3UZ7HS7H26Z0",
    "name": "演出 클라우스 그리고 'and' 제스처 들기 관심 없음 시큰둥 무관심",
    "videoUrl": "https://assets.reflix.dev/previews/L3UZ7HS7H26Z0.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3UZ7HS7H26Z0.webp",
    "category": "dialogue-cinematic",
    "tags": [
      "올리기",
      "클라우스",
      "제스처",
      "무관심",
      "집기",
      "演出",
      "動畫"
    ],
    "duration": 3.931,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L3TR52T5CKKCB",
    "name": "演出 奧術 오열 슬픔 분노 挫敗 絕望 눈물 울기 울음",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T5CKKCB.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T5CKKCB.webp",
    "category": "emotion",
    "tags": [
      "奧術",
      "슬픔",
      "분노",
      "눈물",
      "울기",
      "挫敗",
      "울부짖음",
      "絕望",
      "절규",
      "演出",
      "화남",
      "화내기",
      "침울",
      "우울",
      "動畫"
    ],
    "duration": 10.006,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L3TR52T3EC4OT",
    "name": "演出 호라이즌 인사",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T3EC4OT.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T3EC4OT.webp",
    "category": "daily-other",
    "tags": [
      "호라이즌",
      "안부",
      "演出",
      "電影感"
    ],
    "duration": 1.713107,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L96TUEKA9NN16",
    "name": "遊戲 원신 攻擊 마법 시전 장풍 기공파 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEKA9NN16.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEKA9NN16.webp",
    "category": "magic",
    "tags": [
      "마법",
      "시전",
      "원신",
      "技能",
      "攻擊",
      "遊戲",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 2.659187,
    "width": 1280,
    "height": 720
  },
  {
    "id": "MJPTGQ0W072KH",
    "name": "演出 젠레스존제로 머리 반대 거절",
    "videoUrl": "https://assets.reflix.dev/previews/MJPTGQ0W072KH.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MJPTGQ0W072KH.webp",
    "category": "direction-game",
    "tags": [
      "젠레스존제로",
      "演出",
      "거절",
      "머리",
      "반대",
      "부정",
      "싫음",
      "거부",
      "사양",
      "電影感"
    ],
    "duration": 2.066667,
    "width": 1280,
    "height": 720
  },
  {
    "id": "LO6IBUNCWMMLJ",
    "name": "遊戲 원신 선택 女性 5",
    "videoUrl": "https://assets.reflix.dev/previews/LO6IBUNCWMMLJ.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LO6IBUNCWMMLJ.webp",
    "category": "selection",
    "tags": [
      "원신",
      "遊戲",
      "선택",
      "女性",
      "인遊戲"
    ],
    "duration": 2.366667,
    "width": 1920,
    "height": 1080
  },
  {
    "id": "L3TR52T32WAXW",
    "name": "演出 奧術 한숨 달갑지 않음 짜증 별로",
    "videoUrl": "https://assets.reflix.dev/previews/L3TR52T32WAXW.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L3TR52T32WAXW.webp",
    "category": "emotion",
    "tags": [
      "奧術",
      "짜증",
      "한숨",
      "演出",
      "걱정",
      "고민",
      "불안",
      "두려움",
      "무서움",
      "공포",
      "겁먹음",
      "動畫"
    ],
    "duration": 4.375,
    "width": 1280,
    "height": 720
  },
  {
    "id": "LI34IOZE11JXK",
    "name": "遊戲 유승진 서머너즈워 크로니클 劍 盾牌 雙持 跳躍 내려찍기",
    "videoUrl": "https://assets.reflix.dev/previews/LI34IOZE11JXK.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LI34IOZE11JXK.webp",
    "category": "sword",
    "tags": [
      "遊戲",
      "劍",
      "雙持",
      "跳躍",
      "유승진",
      "서머너즈워",
      "크로니클",
      "내려찍기",
      "盾牌",
      "攻擊",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 2.067,
    "width": 1280,
    "height": 720
  },
  {
    "id": "LP56H8Q5YBQ90",
    "name": "演出 나라카 遊戲 내려찍기 跳躍 한손 劍 단劍",
    "videoUrl": "https://assets.reflix.dev/previews/LP56H8Q5YBQ90.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/LP56H8Q5YBQ90.webp",
    "category": "jump",
    "tags": [
      "演出",
      "한손",
      "劍",
      "遊戲",
      "短劍",
      "跳躍",
      "내려찍기",
      "나라카",
      "電影感"
    ],
    "duration": 7.4,
    "width": 1280,
    "height": 720
  },
  {
    "id": "L96TUEK8J5Y51",
    "name": "遊戲 劍은사막 아처 格鬥가 날라차기 收招 跳躍 1",
    "videoUrl": "https://assets.reflix.dev/previews/L96TUEK8J5Y51.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/L96TUEK8J5Y51.webp",
    "category": "bow",
    "tags": [
      "黑色沙漠",
      "格鬥가",
      "날라차기",
      "跳躍",
      "收招",
      "궁수",
      "弓箭",
      "몸",
      "攻擊",
      "遊戲",
      "무기",
      "교전",
      "인遊戲"
    ],
    "duration": 4.35,
    "width": 1280,
    "height": 960
  },
  {
    "id": "MO9ZAAZBOKKKC",
    "name": "遊戲 女性 雙持 5타+ 槍 연계 攻擊 콤보 突刺 跳躍 攻擊 올려치기 내려찍기 전투 액션",
    "videoUrl": "https://assets.reflix.dev/previews/MO9ZAAZBOKKKC.mp4",
    "thumbnailUrl": "https://assets.reflix.dev/thumbnails/MO9ZAAZBOKKKC.webp",
    "category": "spear",
    "tags": [
      "遊戲",
      "女性",
      "雙持",
      "5타+",
      "槍",
      "연계 攻擊",
      "콤보",
      "突刺",
      "跳躍 攻擊",
      "올려치기",
      "내려찍기",
      "전투",
      "액션"
    ],
    "duration": 5.379005,
    "width": 1920,
    "height": 1080
  }
];
